include::_attributes.adoc[]

[state=no-title-footer]
== Scoped Values

== Teaser

[quote]
____
The enterprise bean must not attempt to manage threads. *The enterprise bean must not attempt to start*, stop, suspend, or resume *a thread*, or to change a thread’s priority or name. The enterprise bean must not attempt to manage thread groups.
____

[.center]
--
Quelle: https://jakarta.ee/specifications/enterprise-beans/4.0/jakarta-enterprise-beans-spec-core-4.0.html#a9535[Jakarta® Enterprise Beans, Core Features, Version 4.0 Final]

&nbsp; +

[.heading]
Warum?
--

[.step]
* Antwort (ebendort):
+
____
These functions are reserved for the Enterprise Beans container. Allowing the enterprise bean to manage threads would decrease the container’s ability to properly manage the runtime environment.
____

== Problemstellung

[plantuml, Aufrufkette, svg]
....
@startuml
scale 2
Controller -> Request: authenticate(request)
create User
Request -> User
Controller -> Service1: processRequest(requestData)
Service1 -> Service2: handleItem(itemData)
Service2 -> Repository: updateItem(itemData)
Repository -> User: hasPermission()
note right: Woher kommt der User?
@enduml
....

[.step]
* Lösung: `ThreadLocal`

[.columns]
== Thread lokal Variables

[.top]
--
&nbsp; +

* Lebenszeit an Thread gebunden +
  (Vorsicht: Memory-Leak)
* Ein Exemplar je Thread +
  wg. `set`-Methode +
  (teuer)
* Für Kontextinformationen +
  (z. B. aktueller User)

&nbsp; +
&nbsp; +

[.heading]
Was gibt der Test aus?
--

--
[source, java, indent=0]
----
include::{demo}/src/test/java/com/anderscore/goldschmiede/loom/scopedvalules/ThreadLocalTest.java[tags=threadLocal]
----
--

== Scoped Values

* Gleicher Verwendungszweck wie `ThreadLocal`
* Lebenszeit ist an Ausführungskontext gebunden
* Wird *ausschließlich* innerhalb von `StructuredTaskScope` vererbt
* Unveränderlich (kein set)
* Sollte immutable sein (z. B. Record)
* Rebinding für geschachtelten Ausführungskontext möglich (z. B. für sudo)

== Verwendung von Scoped Values

[source, java, indent=0]
.Scoped Value deklarieren
----
include::{demo}/src/test/java/com/anderscore/goldschmiede/loom/scopedvalules/ScopedValuesTest.java[tags=scoped]
----

&nbsp; +

[source, java, indent=0]
.Scoped Value setzen
----
include::{demo}/src/test/java/com/anderscore/goldschmiede/loom/scopedvalules/ScopedValuesTest.java[tags=where]
----

&nbsp; +

[source, java, indent=0]
.Scoped Value auslesen (ähnlich _Optional_)
----
include::{demo}/src/test/java/com/anderscore/goldschmiede/loom/scopedvalules/ScopedValuesTest.java[tags=read]
----
